let map = {
  信息完整性: "integrity",
  数据说明: "declaration",
  源文件类型: "fileType",
  获取方式: "sourceType",
  数据置信度: "reliability",
  公布表格表名: "sheetName",
  公布表格合格条目数: "qualifiedNum",
  公布表格不合格条目数: "unqualifiedNum",
  公布总抽检批次数: "total",
  公布合格率: "qualifiedRate",
  处理的表格是否齐全: "isComplete",
  备注: "memo",
  公告附件数量: "attachmentNum",
  是否存在合并单元格: "isCombine",
  公告id: "notificationId",
  公告snapshot_id: "snapshotId",
  数据源名称: "dataSource",
  数据源类型: "dataSourceType",
  所属网站: "belongWebsite",
  所属网站URL: "belongWebsiteUrl",
  采集时间: "collectTime",
  采集人: "collectPerson",
  发布时间: "publishTime",
  发布主体: "publisher",
  公告标题: "notificationTitle",
  处理时间: "processTime",
  处理人: "processor",
  表格id: "sheetId",
  网址: "url",
};

let mainFields = [
  "信息完整性",
  "数据说明",
  "源文件类型",
  "获取方式",
  "数据置信度",
  "公布表格表名",
  "公布表格合格条目数",
  "公布表格不合格条目数",
  "公布总抽检批次数",
  "公布合格率",
  "处理的表格是否齐全",
  "备注",
  "公告附件数量",
  "是否存在合并单元格",
  "公告id",
  "公告snapshot_id",
];

module.exports = {
  map,
  mainFields,
};
